### ISSUE TITLE
有关优化

### ISSUE THREAD

**Issue by DeweyMeta** [10-OASIS-01/Compiler-NEU-2024-#2]
推荐使用CMake管理项目 文件太多了 每次有改动重新编译太耗时
项目文件夹名称不太好  一般头文件夹名称叫include 源文件夹叫src 其它的资源文件叫res（这只是约定俗成 具体叫什么随意）
搞个CL吧  逼格能更高点

**Comment by 10-OASIS-01** [comment]
首先，非常感谢你提出的宝贵意见！对于没有及时回复表示歉意，感谢你的耐心。

关于你建议使用 CMake 来管理项目，确实如你所说，CMake 可以有效简化构建过程，尤其是在文件较多的情况下，可以减少每次修改后的编译时间。针对文件命名的问题，我已经根据你的建议重新进行了调整，并且在后续的更新中，我会考虑引入 CMake 来进一步优化项目管理和构建流程。

至于为什么目前没有使用 CMake，主要是因为在项目开发初期，我的主要目标是便于在 Visual Studio 环境中进行调试，因此没有采用 CMake。未来，我会考虑完善项目的构建管理方式，以提升开发效率。

另外，关于没有使用命令行（CLI）的问题，主要有两个原因：其一，这个项目是在 Visual Studio 2022 环境下开发的，IDE 提供了更多的调试功能；其二，这个项目主要面向大二的学弟学妹，考虑到他们对图形化界面的理解和上手的便利性，我认为图形化界面更有助于他们快速熟悉这个代码。

再次感谢你的宝贵建议，我会在后续继续改进项目。如果你有更多的想法或建议，欢迎随时交流！

祝好，
Léon
